import React, { useState } from 'react';
import { Sparkles, RefreshCw, Zap } from 'lucide-react';
import { useAIStatus, useAIExplanation } from '../../hooks/useAI';
import type { AIExplainRequest } from '../../types';
import './AIInsightsPanel.css';

type QuestionType = 'mechanism' | 'ic50' | 'druglike' | 'disease_gene';
type EntityType = 'compound' | 'target' | 'disease';

interface AIInsightsPanelProps {
  entityType: EntityType;
  entityId: string;
  entityName: string;
}

const QUESTION_TABS: { id: QuestionType; label: string }[] = [
  { id: 'mechanism', label: 'Mechanism' },
  { id: 'ic50', label: 'IC50 / Potency' },
  { id: 'druglike', label: 'Drug-likeness' },
  { id: 'disease_gene', label: 'Disease Link' },
];

const AIInsightsPanel: React.FC<AIInsightsPanelProps> = ({
  entityType,
  entityId,
  entityName,
}) => {
  const [activeQuestion, setActiveQuestion] = useState<QuestionType>('mechanism');
  const [requested, setRequested] = useState(false);

  const { data: statusData } = useAIStatus();
  const aiEnabled = statusData?.ai_enabled ?? false;

  const request: AIExplainRequest | null = requested
  ? {
      entity_type: entityType,
      entity_id: entityId,
      entity_name: entityName,
      question_type: activeQuestion,
    }
  : null;

  const { data, isLoading, isError } = useAIExplanation(request);

  const handleTabChange = (q: QuestionType) => {
    setActiveQuestion(q);
    setRequested(false);
  };

  const handleRequest = () => setRequested(true);

  if (!aiEnabled) {
    return (
      <div className="ai-panel ai-panel--disabled">
        <div className="ai-panel__header">
          <Sparkles size={16} className="ai-panel__icon" />
          <span className="ai-panel__title">AI Insights</span>
        </div>
        <p className="ai-panel__disabled-msg">
          AI insights are currently disabled. Set <code>AI_ENABLED=true</code> in your backend
          environment to enable Claude Haiku explanations.
        </p>
      </div>
    );
  }

  return (
    <div className="ai-panel">
      <div className="ai-panel__header">
        <div className="ai-panel__header-left">
          <Sparkles size={16} className="ai-panel__icon" />
          <span className="ai-panel__title">AI Insights</span>
          <span className="ai-panel__subtitle">Powered by Claude Haiku</span>
        </div>
        {data?.from_cache && (
          <span className="ai-panel__cache-badge">Cached</span>
        )}
      </div>

      <div className="ai-panel__tabs">
        {QUESTION_TABS.map((tab) => (
          <button
            key={tab.id}
            type="button"
            className={`ai-panel__tab ${activeQuestion === tab.id ? 'ai-panel__tab--active' : ''}`}
            onClick={() => handleTabChange(tab.id)}
          >
            {tab.label}
          </button>
        ))}
      </div>

      <div className="ai-panel__content">
        {!requested && (
          <div className="ai-panel__prompt">
            <p className="ai-panel__prompt-text">
              Get a plain-English explanation of <strong>{entityName}</strong>
              {activeQuestion === 'mechanism' && ' — how it works at a molecular level.'}
              {activeQuestion === 'ic50' && ' — its potency and binding activity data.'}
              {activeQuestion === 'druglike' && ' — its drug-likeness and ADMET properties.'}
              {activeQuestion === 'disease_gene' && ' — its connection to diseases and gene targets.'}
            </p>
            <button
              type="button"
              className="ai-panel__btn"
              onClick={handleRequest}
            >
              <Zap size={14} />
              Get AI Explanation
            </button>
          </div>
        )}

        {requested && isLoading && (
          <div className="ai-panel__loading">
            <div className="ai-panel__spinner" />
            <span>Claude is thinking…</span>
          </div>
        )}

        {requested && isError && (
          <div className="ai-panel__error">
            <p>Failed to get explanation. The AI service may be temporarily unavailable.</p>
            <button
              type="button"
              className="ai-panel__btn ai-panel__btn--sm"
              onClick={handleRequest}
            >
              <RefreshCw size={13} />
              Try again
            </button>
          </div>
        )}

        {requested && data?.explanation && (
          <div className="ai-panel__explanation">
            <p className="ai-panel__text">{data.explanation}</p>
            <div className="ai-panel__footer">
              <span className="ai-panel__attribution">
                Generated by Claude Haiku · Not medical advice
              </span>
              <button
                type="button"
                className="ai-panel__refresh"
                onClick={() => setRequested(false)}
                title="Ask a different question"
              >
                <RefreshCw size={13} />
                Change question
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default AIInsightsPanel;
